---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-hunter
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kube-hunter
        spec:
          containers:
            - name: kube-hunter
              image: aquasec/kube-hunter:0.6.8
              command: ["kube-hunter"]
              args: ["--pod"]
          restartPolicy: Never