apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-21T17:02:12Z"
  generateName: argocd-dex-server-59bd76d76-
  labels:
    app.kubernetes.io/name: argocd-dex-server
    pod-template-hash: 59bd76d76
  name: argocd-dex-server-59bd76d76-rqlbl
  namespace: argocd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: argocd-dex-server-59bd76d76
    uid: 30fdaf74-0f80-4bd2-8765-9ab0339ce41c
  resourceVersion: "29467"
  uid: 4dcd00fa-b8c1-4be4-85e5-03b764672be3
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: argocd
          topologyKey: kubernetes.io/hostname
        weight: 5
  containers:
  - command:
    - /shared/argocd-dex
    - rundex
    env:
    - name: ARGOCD_DEX_SERVER_DISABLE_TLS
      valueFrom:
        configMapKeyRef:
          key: dexserver.disable.tls
          name: argocd-cmd-params-cm
          optional: true
    image: ghcr.io/dexidp/dex:v2.37.0
    imagePullPolicy: Always
    name: dex
    ports:
    - containerPort: 5556
      protocol: TCP
    - containerPort: 5557
      protocol: TCP
    - containerPort: 5558
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /shared
      name: static-files
    - mountPath: /tmp
      name: dexconfig
    - mountPath: /tls
      name: argocd-dex-server-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-l8nqf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - /bin/cp
    - -n
    - /usr/local/bin/argocd
    - /shared/argocd-dex
    image: quay.io/argoproj/argocd:v2.10.6
    imagePullPolicy: Always
    name: copyutil
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /shared
      name: static-files
    - mountPath: /tmp
      name: dexconfig
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-l8nqf
      readOnly: true
  nodeName: ip-10-0-23-161.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: argocd-dex-server
  serviceAccountName: argocd-dex-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: static-files
  - emptyDir: {}
    name: dexconfig
  - name: argocd-dex-server-tls
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
      - key: ca.crt
        path: ca.crt
      optional: true
      secretName: argocd-dex-server-tls
  - name: kube-api-access-l8nqf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-21T17:04:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-21T17:07:36Z"
    message: 'containers with unready status: [dex]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-21T17:07:36Z"
    message: 'containers with unready status: [dex]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-21T17:03:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c7783213b10311c45f8621be6b1d9c96fdc745e1e350f2726ef7fa4206f2a7c2
    image: ghcr.io/dexidp/dex:v2.37.0
    imageID: ghcr.io/dexidp/dex@sha256:f579d00721b0d842328c43a562f50343c54b0048ef2d58d6b54e750c21fc7938
    lastState:
      terminated:
        containerID: containerd://c7783213b10311c45f8621be6b1d9c96fdc745e1e350f2726ef7fa4206f2a7c2
        exitCode: 20
        finishedAt: "2024-04-21T17:07:35Z"
        reason: Error
        startedAt: "2024-04-21T17:07:34Z"
    name: dex
    ready: false
    restartCount: 5
    started: false
    state:
      waiting:
        message: back-off 2m40s restarting failed container=dex pod=argocd-dex-server-59bd76d76-rqlbl_argocd(4dcd00fa-b8c1-4be4-85e5-03b764672be3)
        reason: CrashLoopBackOff
  hostIP: 10.0.23.161
  initContainerStatuses:
  - containerID: containerd://66078e087aaaf5b4c761e613372644fa0cb786dbf9ade86d77a6d843dfe58602
    image: quay.io/argoproj/argocd:v2.10.6
    imageID: quay.io/argoproj/argocd@sha256:2cbdc438331df8b9fc7ac68481c36949726ecfc6821cb660fc1a7c2ede012b98
    lastState: {}
    name: copyutil
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://66078e087aaaf5b4c761e613372644fa0cb786dbf9ade86d77a6d843dfe58602
        exitCode: 0
        finishedAt: "2024-04-21T17:04:24Z"
        reason: Completed
        startedAt: "2024-04-21T17:04:24Z"
  phase: Running
  podIP: 10.0.20.252
  podIPs:
  - ip: 10.0.20.252
  qosClass: BestEffort
  startTime: "2024-04-21T17:03:38Z"
